module.exports = [
  {
    name: "format",
    label: "Category",
    type: "select",
    options: [
      "Heavy Metal",
      "Folk",
      "10” Vinyl",
      "Children’s",
      "Latin",
      "Soundtracks",
      "R & B",
      "Punk",
      "Jazz",
      "Electronic",
      "Hip Hop",
      "Country",
      "Vintage",
      "DVDs",
      "Art",
      "Cassettes",
      "Classical",
      "Blues",
      "International",
      "Reggae",
      "Holiday",
      "Store Merch",
      "On Sale",
      "Non-Music",
      "12” Vinyl",
      "CDs",
      "Gift Cards",
      "7” Vinyl",
      "Vinyl",
      "Rock & Pop",
      "Memorabilia",
      "Vault",
      "Books",
      "Collectibles",
      "New Arrival",
    ],
  },
  {
    name: "artist",
    label: "Artist",
    type: "string",
  },
  {
    name: "title",
    label: "Title",
    type: "string",
  },
  {
    name: "upc",
    label: "UPC",
    type: "string",
  },
  {
    name: "genre",
    label: "Genre",
    type: "select",
    options: [
      "Rock & Pop",
      "Heavy Metal",
      "Hip Hop",
      "Blues",
      "Country",
      "Jazz",
      "R & B",
      "Punk",
      "Electronic",
      "Folk",
      "Reggae",
      "Latin",
      "International",
      "Soundtracks",
      "Non-Music",
      "Children’s",
      "Holiday",
      "Classical",
    ],
  },
  {
    name: "size",
    label: "Size",
    type: "select",
    options: ['12"', '10"', '7"'],
  },
  {
    name: "catalog",
    label: "Catalog #",
    type: "string",
  },
  { name: "recordLabel", label: "Record Label", type: "string" },
  { name: "year", label: "Release year / Year", type: "string" },
  { name: "country", label: "Country of Manufacture", type: "string" },
];
